### ISSUE TITLE
Can not find cranfield_gt_no_commas.csv file

### ISSUE THREAD

**Issue by mubashirqasim** [rustyoldrake/R_Scripts_for_Watson#1]
Hi there,

First of all thanks for sharing hands on code. It is indeed awesome!
Hey I could not find cranfield_gt_no_commas.csv among the file. Is there any way I can have it?

Many thanks,

Mubashir

**Comment by rustyoldrake** [comment]
Hi Mubashir!  sorry for delay  - here is the file 
https://drive.google.com/file/d/0B6h8U_pBdhXHamxiSTBkcjVQNFk/view?usp=sharing

**Comment by mubashirqasim** [comment]
Thanks for the data rustyoldrake... Really appreciate that!
